//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverProV2.WCF_AntaraIntegrationBBVA {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sp_ConsultarSeccion2_Result", Namespace="http://schemas.datacontract.org/2004/07/Wcf_IntegrationBBVA.Models")]
    [System.SerializableAttribute()]
    public partial class sp_ConsultarSeccion2_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCampoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumCapturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCampo {
            get {
                return this.NombreCampoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCampoField, value) != true)) {
                    this.NombreCampoField = value;
                    this.RaisePropertyChanged("NombreCampo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumCaptura {
            get {
                return this.NumCapturaField;
            }
            set {
                if ((this.NumCapturaField.Equals(value) != true)) {
                    this.NumCapturaField = value;
                    this.RaisePropertyChanged("NumCaptura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                if ((object.ReferenceEquals(this.valorField, value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sp_ConsultarObservacionesCheckList_Result", Namespace="http://schemas.datacontract.org/2004/07/Wcf_IntegrationBBVA.Models")]
    [System.SerializableAttribute()]
    public partial class sp_ConsultarObservacionesCheckList_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdArea {
            get {
                return this.IdAreaField;
            }
            set {
                if ((this.IdAreaField.Equals(value) != true)) {
                    this.IdAreaField = value;
                    this.RaisePropertyChanged("IdArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstado {
            get {
                return this.IdEstadoField;
            }
            set {
                if ((this.IdEstadoField.Equals(value) != true)) {
                    this.IdEstadoField = value;
                    this.RaisePropertyChanged("IdEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sp_ConsultarOficinas_Result", Namespace="http://schemas.datacontract.org/2004/07/Wcf_IntegrationBBVA.Models")]
    [System.SerializableAttribute()]
    public partial class sp_ConsultarOficinas_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodDescripcion {
            get {
                return this.CodDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodDescripcionField, value) != true)) {
                    this.CodDescripcionField = value;
                    this.RaisePropertyChanged("CodDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codId {
            get {
                return this.codIdField;
            }
            set {
                if ((object.ReferenceEquals(this.codIdField, value) != true)) {
                    this.codIdField = value;
                    this.RaisePropertyChanged("codId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="spCalculosSimuladorDesembolsoLib_Result", Namespace="http://schemas.datacontract.org/2004/07/Wcf_IntegrationBBVA.Models")]
    [System.SerializableAttribute()]
    public partial class spCalculosSimuladorDesembolsoLib_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LlaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Llave {
            get {
                return this.LlaveField;
            }
            set {
                if ((object.ReferenceEquals(this.LlaveField, value) != true)) {
                    this.LlaveField = value;
                    this.RaisePropertyChanged("Llave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sp_ConsultarCamposCheckL_Result", Namespace="http://schemas.datacontract.org/2004/07/Wcf_IntegrationBBVA.Models")]
    [System.SerializableAttribute()]
    public partial class sp_ConsultarCamposCheckL_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCampoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCapturaCheckListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IndiceGrillaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCampo {
            get {
                return this.IdCampoField;
            }
            set {
                if ((this.IdCampoField.Equals(value) != true)) {
                    this.IdCampoField = value;
                    this.RaisePropertyChanged("IdCampo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCapturaCheckList {
            get {
                return this.IdCapturaCheckListField;
            }
            set {
                if ((this.IdCapturaCheckListField.Equals(value) != true)) {
                    this.IdCapturaCheckListField = value;
                    this.RaisePropertyChanged("IdCapturaCheckList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IndiceGrilla {
            get {
                return this.IndiceGrillaField;
            }
            set {
                if ((this.IndiceGrillaField.Equals(value) != true)) {
                    this.IndiceGrillaField = value;
                    this.RaisePropertyChanged("IndiceGrilla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                if ((object.ReferenceEquals(this.valorField, value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sp_ConsultarCamposAnlisisLib_Result", Namespace="http://schemas.datacontract.org/2004/07/Wcf_IntegrationBBVA.Models")]
    [System.SerializableAttribute()]
    public partial class sp_ConsultarCamposAnlisisLib_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCampoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCapturaAnalisisLibField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IndiceGrillaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCampo {
            get {
                return this.IdCampoField;
            }
            set {
                if ((this.IdCampoField.Equals(value) != true)) {
                    this.IdCampoField = value;
                    this.RaisePropertyChanged("IdCampo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCapturaAnalisisLib {
            get {
                return this.IdCapturaAnalisisLibField;
            }
            set {
                if ((this.IdCapturaAnalisisLibField.Equals(value) != true)) {
                    this.IdCapturaAnalisisLibField = value;
                    this.RaisePropertyChanged("IdCapturaAnalisisLib");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IndiceGrilla {
            get {
                return this.IndiceGrillaField;
            }
            set {
                if ((this.IndiceGrillaField.Equals(value) != true)) {
                    this.IndiceGrillaField = value;
                    this.RaisePropertyChanged("IndiceGrilla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                if ((object.ReferenceEquals(this.valorField, value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sp_ConsultarMinisabanas_Result", Namespace="http://schemas.datacontract.org/2004/07/Wcf_IntegrationBBVA.Models")]
    [System.SerializableAttribute()]
    public partial class sp_ConsultarMinisabanas_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCampoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCapturaAnalisisLibField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IndiceGrillaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCampo {
            get {
                return this.IdCampoField;
            }
            set {
                if ((this.IdCampoField.Equals(value) != true)) {
                    this.IdCampoField = value;
                    this.RaisePropertyChanged("IdCampo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCapturaAnalisisLib {
            get {
                return this.IdCapturaAnalisisLibField;
            }
            set {
                if ((this.IdCapturaAnalisisLibField.Equals(value) != true)) {
                    this.IdCapturaAnalisisLibField = value;
                    this.RaisePropertyChanged("IdCapturaAnalisisLib");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IndiceGrilla {
            get {
                return this.IndiceGrillaField;
            }
            set {
                if ((this.IndiceGrillaField.Equals(value) != true)) {
                    this.IndiceGrillaField = value;
                    this.RaisePropertyChanged("IndiceGrilla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                if ((object.ReferenceEquals(this.valorField, value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sp_ConsultarCamposAnlisisCon_Result", Namespace="http://schemas.datacontract.org/2004/07/Wcf_IntegrationBBVA.Models")]
    [System.SerializableAttribute()]
    public partial class sp_ConsultarCamposAnlisisCon_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCampoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCapturaAnalisisConField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IndiceGrillaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCampo {
            get {
                return this.IdCampoField;
            }
            set {
                if ((this.IdCampoField.Equals(value) != true)) {
                    this.IdCampoField = value;
                    this.RaisePropertyChanged("IdCampo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCapturaAnalisisCon {
            get {
                return this.IdCapturaAnalisisConField;
            }
            set {
                if ((this.IdCapturaAnalisisConField.Equals(value) != true)) {
                    this.IdCapturaAnalisisConField = value;
                    this.RaisePropertyChanged("IdCapturaAnalisisCon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IndiceGrilla {
            get {
                return this.IndiceGrillaField;
            }
            set {
                if ((this.IndiceGrillaField.Equals(value) != true)) {
                    this.IndiceGrillaField = value;
                    this.RaisePropertyChanged("IndiceGrilla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                if ((object.ReferenceEquals(this.valorField, value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sp_ConsultarCamposAnlisisVeh_Result", Namespace="http://schemas.datacontract.org/2004/07/Wcf_IntegrationBBVA.Models")]
    [System.SerializableAttribute()]
    public partial class sp_ConsultarCamposAnlisisVeh_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCampoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCapturaAnalisisVehField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IndiceGrillaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NoTitularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCampo {
            get {
                return this.IdCampoField;
            }
            set {
                if ((this.IdCampoField.Equals(value) != true)) {
                    this.IdCampoField = value;
                    this.RaisePropertyChanged("IdCampo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCapturaAnalisisVeh {
            get {
                return this.IdCapturaAnalisisVehField;
            }
            set {
                if ((this.IdCapturaAnalisisVehField.Equals(value) != true)) {
                    this.IdCapturaAnalisisVehField = value;
                    this.RaisePropertyChanged("IdCapturaAnalisisVeh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IndiceGrilla {
            get {
                return this.IndiceGrillaField;
            }
            set {
                if ((this.IndiceGrillaField.Equals(value) != true)) {
                    this.IndiceGrillaField = value;
                    this.RaisePropertyChanged("IndiceGrilla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NoTitular {
            get {
                return this.NoTitularField;
            }
            set {
                if ((this.NoTitularField.Equals(value) != true)) {
                    this.NoTitularField = value;
                    this.RaisePropertyChanged("NoTitular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                if ((object.ReferenceEquals(this.valorField, value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultarCamposAutoSave_Result", Namespace="http://schemas.datacontract.org/2004/07/Wcf_IntegrationBBVA.Models")]
    [System.SerializableAttribute()]
    public partial class ConsultarCamposAutoSave_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCampoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCapturaAutoSaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IndiceGrillaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NoTitularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCampo {
            get {
                return this.IdCampoField;
            }
            set {
                if ((this.IdCampoField.Equals(value) != true)) {
                    this.IdCampoField = value;
                    this.RaisePropertyChanged("IdCampo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCapturaAutoSave {
            get {
                return this.IdCapturaAutoSaveField;
            }
            set {
                if ((this.IdCapturaAutoSaveField.Equals(value) != true)) {
                    this.IdCapturaAutoSaveField = value;
                    this.RaisePropertyChanged("IdCapturaAutoSave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IndiceGrilla {
            get {
                return this.IndiceGrillaField;
            }
            set {
                if ((this.IndiceGrillaField.Equals(value) != true)) {
                    this.IndiceGrillaField = value;
                    this.RaisePropertyChanged("IndiceGrilla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NoTitular {
            get {
                return this.NoTitularField;
            }
            set {
                if ((this.NoTitularField.Equals(value) != true)) {
                    this.NoTitularField = value;
                    this.RaisePropertyChanged("NoTitular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                if ((object.ReferenceEquals(this.valorField, value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sp_ConsultarCamposActualizacionclientes_Result", Namespace="http://schemas.datacontract.org/2004/07/Wcf_IntegrationBBVA.Models")]
    [System.SerializableAttribute()]
    public partial class sp_ConsultarCamposActualizacionclientes_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdActualizacionClientesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCampoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IndiceGrillaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdActualizacionClientes {
            get {
                return this.IdActualizacionClientesField;
            }
            set {
                if ((this.IdActualizacionClientesField.Equals(value) != true)) {
                    this.IdActualizacionClientesField = value;
                    this.RaisePropertyChanged("IdActualizacionClientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCampo {
            get {
                return this.IdCampoField;
            }
            set {
                if ((this.IdCampoField.Equals(value) != true)) {
                    this.IdCampoField = value;
                    this.RaisePropertyChanged("IdCampo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IndiceGrilla {
            get {
                return this.IndiceGrillaField;
            }
            set {
                if ((this.IndiceGrillaField.Equals(value) != true)) {
                    this.IndiceGrillaField = value;
                    this.RaisePropertyChanged("IndiceGrilla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                if ((object.ReferenceEquals(this.valorField, value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sp_ConsultarEnviosDesemsolsos_Result", Namespace="http://schemas.datacontract.org/2004/07/Wcf_IntegrationBBVA.Models")]
    [System.SerializableAttribute()]
    public partial class sp_ConsultarEnviosDesemsolsos_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaEnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GruiIdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> RespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idRadicadoBonitaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destino {
            get {
                return this.DestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinoField, value) != true)) {
                    this.DestinoField = value;
                    this.RaisePropertyChanged("Destino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaEnvio {
            get {
                return this.FechaEnvioField;
            }
            set {
                if ((this.FechaEnvioField.Equals(value) != true)) {
                    this.FechaEnvioField = value;
                    this.RaisePropertyChanged("FechaEnvio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GruiIdProducto {
            get {
                return this.GruiIdProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.GruiIdProductoField, value) != true)) {
                    this.GruiIdProductoField = value;
                    this.RaisePropertyChanged("GruiIdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origen {
            get {
                return this.OrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.OrigenField, value) != true)) {
                    this.OrigenField = value;
                    this.RaisePropertyChanged("Origen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((this.RespuestaField.Equals(value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idRadicadoBonita {
            get {
                return this.idRadicadoBonitaField;
            }
            set {
                if ((this.idRadicadoBonitaField.Equals(value) != true)) {
                    this.idRadicadoBonitaField = value;
                    this.RaisePropertyChanged("idRadicadoBonita");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clasesResult", Namespace="http://schemas.datacontract.org/2004/07/Wcf_IntegrationBBVA")]
    [System.SerializableAttribute()]
    public partial class clasesResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdRadicadoBonitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesDactiloscopiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdRadicadoBonita {
            get {
                return this.IdRadicadoBonitaField;
            }
            set {
                if ((this.IdRadicadoBonitaField.Equals(value) != true)) {
                    this.IdRadicadoBonitaField = value;
                    this.RaisePropertyChanged("IdRadicadoBonita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((object.ReferenceEquals(this.MontoField, value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservacionesDactiloscopia {
            get {
                return this.ObservacionesDactiloscopiaField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesDactiloscopiaField, value) != true)) {
                    this.ObservacionesDactiloscopiaField = value;
                    this.RaisePropertyChanged("ObservacionesDactiloscopia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="spHipoConsultarRadicado_Result", Namespace="http://schemas.datacontract.org/2004/07/Wcf_IntegrationBBVA.Models")]
    [System.SerializableAttribute()]
    public partial class spHipoConsultarRadicado_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCampoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCapturaHipoScoringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndiceGrillaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NoTitularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCampo {
            get {
                return this.IdCampoField;
            }
            set {
                if ((this.IdCampoField.Equals(value) != true)) {
                    this.IdCampoField = value;
                    this.RaisePropertyChanged("IdCampo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCapturaHipoScoring {
            get {
                return this.IdCapturaHipoScoringField;
            }
            set {
                if ((this.IdCapturaHipoScoringField.Equals(value) != true)) {
                    this.IdCapturaHipoScoringField = value;
                    this.RaisePropertyChanged("IdCapturaHipoScoring");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IndiceGrilla {
            get {
                return this.IndiceGrillaField;
            }
            set {
                if ((this.IndiceGrillaField.Equals(value) != true)) {
                    this.IndiceGrillaField = value;
                    this.RaisePropertyChanged("IndiceGrilla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NoTitular {
            get {
                return this.NoTitularField;
            }
            set {
                if ((this.NoTitularField.Equals(value) != true)) {
                    this.NoTitularField = value;
                    this.RaisePropertyChanged("NoTitular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                if ((object.ReferenceEquals(this.valorField, value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_AntaraIntegrationBBVA.IAntaraService")]
    public interface IAntaraService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/LoadFormVCD", ReplyAction="http://tempuri.org/IAntaraService/LoadFormVCDResponse")]
        EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarSeccion2_Result[] LoadFormVCD(string ListCampos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/LoadFormVCD", ReplyAction="http://tempuri.org/IAntaraService/LoadFormVCDResponse")]
        System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarSeccion2_Result[]> LoadFormVCDAsync(string ListCampos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/LoadFormVCDObserva", ReplyAction="http://tempuri.org/IAntaraService/LoadFormVCDObservaResponse")]
        EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarObservacionesCheckList_Result[] LoadFormVCDObserva(string ListCamposs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/LoadFormVCDObserva", ReplyAction="http://tempuri.org/IAntaraService/LoadFormVCDObservaResponse")]
        System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarObservacionesCheckList_Result[]> LoadFormVCDObservaAsync(string ListCamposs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/LoadOficinas", ReplyAction="http://tempuri.org/IAntaraService/LoadOficinasResponse")]
        EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarOficinas_Result[] LoadOficinas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/LoadOficinas", ReplyAction="http://tempuri.org/IAntaraService/LoadOficinasResponse")]
        System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarOficinas_Result[]> LoadOficinasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/CalcularSim_DesembolsoLib", ReplyAction="http://tempuri.org/IAntaraService/CalcularSim_DesembolsoLibResponse")]
        EverProV2.WCF_AntaraIntegrationBBVA.spCalculosSimuladorDesembolsoLib_Result[] CalcularSim_DesembolsoLib(decimal montoSolicitado, decimal compraDeCartera, decimal plazoSolicitado, int numeroCheques, string tasaInteres, string conProyeccion, System.DateTime fechaDesembolso, System.DateTime fechaSinProyeccion, int diaInicioRestriccion, int diaFinRestriccion, int claseDesembolso, int diasVencimiento, int diasPeriodoGracia, int cuotasRetenidas, int subproducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/CalcularSim_DesembolsoLib", ReplyAction="http://tempuri.org/IAntaraService/CalcularSim_DesembolsoLibResponse")]
        System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.spCalculosSimuladorDesembolsoLib_Result[]> CalcularSim_DesembolsoLibAsync(decimal montoSolicitado, decimal compraDeCartera, decimal plazoSolicitado, int numeroCheques, string tasaInteres, string conProyeccion, System.DateTime fechaDesembolso, System.DateTime fechaSinProyeccion, int diaInicioRestriccion, int diaFinRestriccion, int claseDesembolso, int diasVencimiento, int diasPeriodoGracia, int cuotasRetenidas, int subproducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/spConsultarCamposCheckL", ReplyAction="http://tempuri.org/IAntaraService/spConsultarCamposCheckLResponse")]
        EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposCheckL_Result[] spConsultarCamposCheckL(string idRadicadoBonita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/spConsultarCamposCheckL", ReplyAction="http://tempuri.org/IAntaraService/spConsultarCamposCheckLResponse")]
        System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposCheckL_Result[]> spConsultarCamposCheckLAsync(string idRadicadoBonita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/spConsultarCamposAnalisisLib", ReplyAction="http://tempuri.org/IAntaraService/spConsultarCamposAnalisisLibResponse")]
        EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposAnlisisLib_Result[] spConsultarCamposAnalisisLib(string idRadicadoBonita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/spConsultarCamposAnalisisLib", ReplyAction="http://tempuri.org/IAntaraService/spConsultarCamposAnalisisLibResponse")]
        System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposAnlisisLib_Result[]> spConsultarCamposAnalisisLibAsync(string idRadicadoBonita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/HerenciaMinisabanaLibranzas", ReplyAction="http://tempuri.org/IAntaraService/HerenciaMinisabanaLibranzasResponse")]
        EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarMinisabanas_Result[] HerenciaMinisabanaLibranzas(int idRadicadoBonita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/HerenciaMinisabanaLibranzas", ReplyAction="http://tempuri.org/IAntaraService/HerenciaMinisabanaLibranzasResponse")]
        System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarMinisabanas_Result[]> HerenciaMinisabanaLibranzasAsync(int idRadicadoBonita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/spConsultarCamposAnalisisCon", ReplyAction="http://tempuri.org/IAntaraService/spConsultarCamposAnalisisConResponse")]
        EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposAnlisisCon_Result[] spConsultarCamposAnalisisCon(string idRadicadoBonita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/spConsultarCamposAnalisisCon", ReplyAction="http://tempuri.org/IAntaraService/spConsultarCamposAnalisisConResponse")]
        System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposAnlisisCon_Result[]> spConsultarCamposAnalisisConAsync(string idRadicadoBonita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/spConsultarCamposAnalisisVeh", ReplyAction="http://tempuri.org/IAntaraService/spConsultarCamposAnalisisVehResponse")]
        EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposAnlisisVeh_Result[] spConsultarCamposAnalisisVeh(string idRadicadoBonita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/spConsultarCamposAnalisisVeh", ReplyAction="http://tempuri.org/IAntaraService/spConsultarCamposAnalisisVehResponse")]
        System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposAnlisisVeh_Result[]> spConsultarCamposAnalisisVehAsync(string idRadicadoBonita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/spConsultarCamposAutoSave", ReplyAction="http://tempuri.org/IAntaraService/spConsultarCamposAutoSaveResponse")]
        EverProV2.WCF_AntaraIntegrationBBVA.ConsultarCamposAutoSave_Result[] spConsultarCamposAutoSave(string idRadicadoBonita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/spConsultarCamposAutoSave", ReplyAction="http://tempuri.org/IAntaraService/spConsultarCamposAutoSaveResponse")]
        System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.ConsultarCamposAutoSave_Result[]> spConsultarCamposAutoSaveAsync(string idRadicadoBonita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/spConsultarCamposActualizacionclientes", ReplyAction="http://tempuri.org/IAntaraService/spConsultarCamposActualizacionclientesResponse")]
        EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposActualizacionclientes_Result[] spConsultarCamposActualizacionclientes(string idRadicadoBonita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/spConsultarCamposActualizacionclientes", ReplyAction="http://tempuri.org/IAntaraService/spConsultarCamposActualizacionclientesResponse")]
        System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposActualizacionclientes_Result[]> spConsultarCamposActualizacionclientesAsync(string idRadicadoBonita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/spConsultarEnviosDesembolsos", ReplyAction="http://tempuri.org/IAntaraService/spConsultarEnviosDesembolsosResponse")]
        EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarEnviosDesemsolsos_Result[] spConsultarEnviosDesembolsos(string area);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/spConsultarEnviosDesembolsos", ReplyAction="http://tempuri.org/IAntaraService/spConsultarEnviosDesembolsosResponse")]
        System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarEnviosDesemsolsos_Result[]> spConsultarEnviosDesembolsosAsync(string area);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/spConsultarPendientes", ReplyAction="http://tempuri.org/IAntaraService/spConsultarPendientesResponse")]
        EverProV2.WCF_AntaraIntegrationBBVA.clasesResult[] spConsultarPendientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/spConsultarPendientes", ReplyAction="http://tempuri.org/IAntaraService/spConsultarPendientesResponse")]
        System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.clasesResult[]> spConsultarPendientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/spConsultarCamposHipotecario", ReplyAction="http://tempuri.org/IAntaraService/spConsultarCamposHipotecarioResponse")]
        EverProV2.WCF_AntaraIntegrationBBVA.spHipoConsultarRadicado_Result[] spConsultarCamposHipotecario(string idRadicadoBonita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntaraService/spConsultarCamposHipotecario", ReplyAction="http://tempuri.org/IAntaraService/spConsultarCamposHipotecarioResponse")]
        System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.spHipoConsultarRadicado_Result[]> spConsultarCamposHipotecarioAsync(string idRadicadoBonita);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAntaraServiceChannel : EverProV2.WCF_AntaraIntegrationBBVA.IAntaraService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AntaraServiceClient : System.ServiceModel.ClientBase<EverProV2.WCF_AntaraIntegrationBBVA.IAntaraService>, EverProV2.WCF_AntaraIntegrationBBVA.IAntaraService {
        
        public AntaraServiceClient() {
        }
        
        public AntaraServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AntaraServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AntaraServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AntaraServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarSeccion2_Result[] LoadFormVCD(string ListCampos) {
            return base.Channel.LoadFormVCD(ListCampos);
        }
        
        public System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarSeccion2_Result[]> LoadFormVCDAsync(string ListCampos) {
            return base.Channel.LoadFormVCDAsync(ListCampos);
        }
        
        public EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarObservacionesCheckList_Result[] LoadFormVCDObserva(string ListCamposs) {
            return base.Channel.LoadFormVCDObserva(ListCamposs);
        }
        
        public System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarObservacionesCheckList_Result[]> LoadFormVCDObservaAsync(string ListCamposs) {
            return base.Channel.LoadFormVCDObservaAsync(ListCamposs);
        }
        
        public EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarOficinas_Result[] LoadOficinas() {
            return base.Channel.LoadOficinas();
        }
        
        public System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarOficinas_Result[]> LoadOficinasAsync() {
            return base.Channel.LoadOficinasAsync();
        }
        
        public EverProV2.WCF_AntaraIntegrationBBVA.spCalculosSimuladorDesembolsoLib_Result[] CalcularSim_DesembolsoLib(decimal montoSolicitado, decimal compraDeCartera, decimal plazoSolicitado, int numeroCheques, string tasaInteres, string conProyeccion, System.DateTime fechaDesembolso, System.DateTime fechaSinProyeccion, int diaInicioRestriccion, int diaFinRestriccion, int claseDesembolso, int diasVencimiento, int diasPeriodoGracia, int cuotasRetenidas, int subproducto) {
            return base.Channel.CalcularSim_DesembolsoLib(montoSolicitado, compraDeCartera, plazoSolicitado, numeroCheques, tasaInteres, conProyeccion, fechaDesembolso, fechaSinProyeccion, diaInicioRestriccion, diaFinRestriccion, claseDesembolso, diasVencimiento, diasPeriodoGracia, cuotasRetenidas, subproducto);
        }
        
        public System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.spCalculosSimuladorDesembolsoLib_Result[]> CalcularSim_DesembolsoLibAsync(decimal montoSolicitado, decimal compraDeCartera, decimal plazoSolicitado, int numeroCheques, string tasaInteres, string conProyeccion, System.DateTime fechaDesembolso, System.DateTime fechaSinProyeccion, int diaInicioRestriccion, int diaFinRestriccion, int claseDesembolso, int diasVencimiento, int diasPeriodoGracia, int cuotasRetenidas, int subproducto) {
            return base.Channel.CalcularSim_DesembolsoLibAsync(montoSolicitado, compraDeCartera, plazoSolicitado, numeroCheques, tasaInteres, conProyeccion, fechaDesembolso, fechaSinProyeccion, diaInicioRestriccion, diaFinRestriccion, claseDesembolso, diasVencimiento, diasPeriodoGracia, cuotasRetenidas, subproducto);
        }
        
        public EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposCheckL_Result[] spConsultarCamposCheckL(string idRadicadoBonita) {
            return base.Channel.spConsultarCamposCheckL(idRadicadoBonita);
        }
        
        public System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposCheckL_Result[]> spConsultarCamposCheckLAsync(string idRadicadoBonita) {
            return base.Channel.spConsultarCamposCheckLAsync(idRadicadoBonita);
        }
        
        public EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposAnlisisLib_Result[] spConsultarCamposAnalisisLib(string idRadicadoBonita) {
            return base.Channel.spConsultarCamposAnalisisLib(idRadicadoBonita);
        }
        
        public System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposAnlisisLib_Result[]> spConsultarCamposAnalisisLibAsync(string idRadicadoBonita) {
            return base.Channel.spConsultarCamposAnalisisLibAsync(idRadicadoBonita);
        }
        
        public EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarMinisabanas_Result[] HerenciaMinisabanaLibranzas(int idRadicadoBonita) {
            return base.Channel.HerenciaMinisabanaLibranzas(idRadicadoBonita);
        }
        
        public System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarMinisabanas_Result[]> HerenciaMinisabanaLibranzasAsync(int idRadicadoBonita) {
            return base.Channel.HerenciaMinisabanaLibranzasAsync(idRadicadoBonita);
        }
        
        public EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposAnlisisCon_Result[] spConsultarCamposAnalisisCon(string idRadicadoBonita) {
            return base.Channel.spConsultarCamposAnalisisCon(idRadicadoBonita);
        }
        
        public System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposAnlisisCon_Result[]> spConsultarCamposAnalisisConAsync(string idRadicadoBonita) {
            return base.Channel.spConsultarCamposAnalisisConAsync(idRadicadoBonita);
        }
        
        public EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposAnlisisVeh_Result[] spConsultarCamposAnalisisVeh(string idRadicadoBonita) {
            return base.Channel.spConsultarCamposAnalisisVeh(idRadicadoBonita);
        }
        
        public System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposAnlisisVeh_Result[]> spConsultarCamposAnalisisVehAsync(string idRadicadoBonita) {
            return base.Channel.spConsultarCamposAnalisisVehAsync(idRadicadoBonita);
        }
        
        public EverProV2.WCF_AntaraIntegrationBBVA.ConsultarCamposAutoSave_Result[] spConsultarCamposAutoSave(string idRadicadoBonita) {
            return base.Channel.spConsultarCamposAutoSave(idRadicadoBonita);
        }
        
        public System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.ConsultarCamposAutoSave_Result[]> spConsultarCamposAutoSaveAsync(string idRadicadoBonita) {
            return base.Channel.spConsultarCamposAutoSaveAsync(idRadicadoBonita);
        }
        
        public EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposActualizacionclientes_Result[] spConsultarCamposActualizacionclientes(string idRadicadoBonita) {
            return base.Channel.spConsultarCamposActualizacionclientes(idRadicadoBonita);
        }
        
        public System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarCamposActualizacionclientes_Result[]> spConsultarCamposActualizacionclientesAsync(string idRadicadoBonita) {
            return base.Channel.spConsultarCamposActualizacionclientesAsync(idRadicadoBonita);
        }
        
        public EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarEnviosDesemsolsos_Result[] spConsultarEnviosDesembolsos(string area) {
            return base.Channel.spConsultarEnviosDesembolsos(area);
        }
        
        public System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.sp_ConsultarEnviosDesemsolsos_Result[]> spConsultarEnviosDesembolsosAsync(string area) {
            return base.Channel.spConsultarEnviosDesembolsosAsync(area);
        }
        
        public EverProV2.WCF_AntaraIntegrationBBVA.clasesResult[] spConsultarPendientes() {
            return base.Channel.spConsultarPendientes();
        }
        
        public System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.clasesResult[]> spConsultarPendientesAsync() {
            return base.Channel.spConsultarPendientesAsync();
        }
        
        public EverProV2.WCF_AntaraIntegrationBBVA.spHipoConsultarRadicado_Result[] spConsultarCamposHipotecario(string idRadicadoBonita) {
            return base.Channel.spConsultarCamposHipotecario(idRadicadoBonita);
        }
        
        public System.Threading.Tasks.Task<EverProV2.WCF_AntaraIntegrationBBVA.spHipoConsultarRadicado_Result[]> spConsultarCamposHipotecarioAsync(string idRadicadoBonita) {
            return base.Channel.spConsultarCamposHipotecarioAsync(idRadicadoBonita);
        }
    }
}
