//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverProV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodigosCampo
    {
        public int CodCampId { get; set; }
        public string CodId { get; set; }
        public string CodDescripcion { get; set; }
        public Nullable<long> CampId { get; set; }
        public int CodOrden { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string CodPadre { get; set; }
    }
}
