//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverProV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estados
    {
        public Estados()
        {
            this.tbFormalizacion = new HashSet<tbFormalizacion>();
            this.tbLibranza = new HashSet<tbLibranza>();
            this.tbUsuariosPorLider = new HashSet<tbUsuariosPorLider>();
            this.tbProcesosMasivos = new HashSet<tbProcesosMasivos>();
        }
    
        public int IdEstado { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Valor { get; set; }
    
        public virtual ICollection<tbFormalizacion> tbFormalizacion { get; set; }
        public virtual ICollection<tbLibranza> tbLibranza { get; set; }
        public virtual ICollection<tbUsuariosPorLider> tbUsuariosPorLider { get; set; }
        public virtual ICollection<tbProcesosMasivos> tbProcesosMasivos { get; set; }
    }
}
