//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverProV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formulario_Campos
    {
        public int IdFormularioCampos { get; set; }
        public Nullable<int> IdFormulario { get; set; }
        public Nullable<int> IdCampos { get; set; }
        public Nullable<int> OrdenCampo { get; set; }
        public Nullable<int> Obligatorio { get; set; }
    
        public virtual Campos Campos { get; set; }
        public virtual tb_Formularios tb_Formularios { get; set; }
    }
}
