//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverProV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistModuloEverisRRHH
    {
        public Nullable<System.DateTime> FechaActualizacon { get; set; }
        public int Cedula { get; set; }
        public int Empresa { get; set; }
        public System.DateTime FecContratacionTemporal { get; set; }
        public System.DateTime FecContratacionEveris { get; set; }
        public string SalarioEveris { get; set; }
        public int CsrGeco { get; set; }
        public int Pais { get; set; }
        public int Cliente { get; set; }
        public int Proyecto { get; set; }
        public int Cargo { get; set; }
        public int Categoria { get; set; }
        public int Nivel { get; set; }
    }
}
