//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverProV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.RolesMenu = new HashSet<RolesMenu>();
        }
    
        public int IdMenu { get; set; }
        public string DescMenu { get; set; }
        public Nullable<int> IdPadre { get; set; }
        public Nullable<int> IdHijo { get; set; }
        public string Url { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string UrlImage { get; set; }
    
        public virtual ICollection<RolesMenu> RolesMenu { get; set; }
    }
}
