//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverProV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuloEverisRRHH
    {
        public int Cedula { get; set; }
        public int Empresa { get; set; }
        public System.DateTime FecContratacionTemporal { get; set; }
        public System.DateTime FecContratacionEveris { get; set; }
        public string SalarioEveris { get; set; }
        public Nullable<int> CsrGeco { get; set; }
        public Nullable<int> Pais { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<int> Proyecto { get; set; }
        public Nullable<int> Cargo { get; set; }
        public Nullable<int> Categoria { get; set; }
        public Nullable<int> Nivel { get; set; }
    }
}
