//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverProV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Formularios
    {
        public tb_Formularios()
        {
            this.Formulario_Campos = new HashSet<Formulario_Campos>();
        }
    
        public int FormularioId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ICollection<Formulario_Campos> Formulario_Campos { get; set; }
    }
}
