//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverProV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAns
    {
        public int idAns { get; set; }
        public int Area { get; set; }
        public string Proceso { get; set; }
        public int IdActivida { get; set; }
        public string Actividad { get; set; }
        public string Productos { get; set; }
        public int ProXHora { get; set; }
        public int ProdAnsHora { get; set; }
        public int EstandarAviso { get; set; }
    }
}
