//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverProV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHistorial
    {
        public int idHistorial { get; set; }
        public int idClasificacion { get; set; }
        public string Area { get; set; }
        public string Lider { get; set; }
        public string Cedula { get; set; }
        public string NombreCompleto { get; set; }
        public int Nradicado { get; set; }
        public System.DateTime FechaAsignado { get; set; }
    }
}
