//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverProV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLiderProductoFile
    {
        public int IdLider { get; set; }
        public Nullable<int> Cedula { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<int> CodProduct { get; set; }
        public Nullable<int> CampoLista { get; set; }
        public string NomFile { get; set; }
        public int Activo { get; set; }
    }
}
