//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverProV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbMallaTurnos
    {
        public int IdMalla { get; set; }
        public int IdTurno { get; set; }
        public int IdFuncionario { get; set; }
        public int Dia { get; set; }
        public int Mes { get; set; }
        public int Anio { get; set; }
        public string Hdesde { get; set; }
        public string Hhasta { get; set; }
        public int Almuerzo { get; set; }
        public int Breack { get; set; }
        public int EstadoTurno { get; set; }
        public int IdLider { get; set; }
    }
}
