//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverProV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProductos
    {
        public int IdProducto { get; set; }
        public int Codigo { get; set; }
        public string Descripcion { get; set; }
        public int Orden { get; set; }
        public int IdArea { get; set; }
        public int IdCamposLIst { get; set; }
        public int Activo { get; set; }
        public Nullable<int> BtDactiloscopia { get; set; }
    }
}
