//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverProV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProcPorProducto
    {
        public int idProcPorProducto { get; set; }
        public int idProducto { get; set; }
        public string DresProceso { get; set; }
    
        public virtual tbProducto tbProducto { get; set; }
    }
}
