//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverProV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTipologiaConvenio
    {
        public tbTipologiaConvenio()
        {
            this.tbClasificaNivFuncionario = new HashSet<tbClasificaNivFuncionario>();
            this.tbAsignacionCasos = new HashSet<tbAsignacionCasos>();
        }
    
        public string NivelConvenio { get; set; }
        public string Complejidad { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> Proceso { get; set; }
    
        public virtual ICollection<tbClasificaNivFuncionario> tbClasificaNivFuncionario { get; set; }
        public virtual ICollection<tbAsignacionCasos> tbAsignacionCasos { get; set; }
    }
}
