//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverProV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Auditoria = new HashSet<Auditoria>();
            this.UsuariosBloqueados = new HashSet<UsuariosBloqueados>();
            this.UsuariosHistorico = new HashSet<UsuariosHistorico>();
        }
    
        public decimal IdUsuario { get; set; }
        public string UsuarioDominio { get; set; }
        public string NomUsuario { get; set; }
        public string PassCodeUsuario { get; set; }
        public Nullable<int> IdRol { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FecRegistro { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public string SecurityPin { get; set; }
    
        public virtual ICollection<Auditoria> Auditoria { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<UsuariosBloqueados> UsuariosBloqueados { get; set; }
        public virtual ICollection<UsuariosHistorico> UsuariosHistorico { get; set; }
    }
}
